colors:
  primary:
    background: "#1E1E2E" # base
    foreground: "#CDD6F4" # text
    # Bright and dim foreground colors
    dim_foreground: "#CDD6F4" # text
    bright_foreground: "#CDD6F4" # text

  # Cursor colors
  cursor:
    text: "#1E1E2E" # base
    cursor: "#F5E0DC" # rosewater
  vi_mode_cursor:
    text: "#1E1E2E" # base
    cursor: "#B4BEFE" # lavender

  # Search colors
  search:
    matches:
      foreground: "#1E1E2E" # base
      background: "#A6ADC8" # subtext0
    focused_match:
      foreground: "#1E1E2E" # base
      background: "#A6E3A1" # green
    footer_bar:
      foreground: "#1E1E2E" # base
      background: "#A6ADC8" # subtext0

  # Keyboard regex hints
  hints:
    start:
      foreground: "#1E1E2E" # base
      background: "#F9E2AF" # yellow
    end:
      foreground: "#1E1E2E" # base
      background: "#A6ADC8" # subtext0

  # Selection colors
  selection:
    text: "#1E1E2E" # base
    background: "#F5E0DC" # rosewater

  # Normal colors
  normal:
    black: "#45475A" # surface1
    red: "#F38BA8" # red
    green: "#A6E3A1" # green
    yellow: "#F9E2AF" # yellow
    blue: "#89B4FA" # blue
    magenta: "#F5C2E7" # pink
    cyan: "#94E2D5" # teal
    white: "#BAC2DE" # subtext1

  # Bright colors
  bright:
    black: "#585B70" # surface2
    red: "#F38BA8" # red
    green: "#A6E3A1" # green
    yellow: "#F9E2AF" # yellow
    blue: "#89B4FA" # blue
    magenta: "#F5C2E7" # pink
    cyan: "#94E2D5" # teal
    white: "#A6ADC8" # subtext0

  # Dim colors
  dim:
    black: "#45475A" # surface1
    red: "#F38BA8" # red
    green: "#A6E3A1" # green
    yellow: "#F9E2AF" # yellow
    blue: "#89B4FA" # blue
    magenta: "#F5C2E7" # pink
    cyan: "#94E2D5" # teal
    white: "#BAC2DE" # subtext1

  indexed_colors:
    - { index: 16, color: "#F5E0DC" } # Rosewater
    - { index: 17, color: "#f2cdcd" } # Flamingo
    - { index: 18, color: "#f5c2e7" } # Pink
    - { index: 19, color: "#cba6f7" } # Mauve
    - { index: 20, color: "#f38ba8" } # Red
    - { index: 21, color: "#eba0ac" } # Maroon
    - { index: 22, color: "#FAB387" } # Peach
    - { index: 23, color: "#f9e2af" } # Yellow
    - { index: 24, color: "#a6e3a1" } # Green
    - { index: 25, color: "#94e2d5" } # Teal
    - { index: 26, color: "#89dceb" } # Sky
    - { index: 27, color: "#74c7ec" } # Sapphire
    - { index: 28, color: "#89b4fa" } # Blue
    - { index: 29, color: "#b4befe" } # Lavender
    - { index: 30, color: "#cdd6f4" } # Text
    - { index: 31, color: "#bac2de" } # Subtext 1
    - { index: 32, color: "#a6adc8" } # Subtext 0
    - { index: 33, color: "#9399b2" } # Overlay 2
    - { index: 34, color: "#7f849c" } # Overlay 1
    - { index: 35, color: "#6c7086" } # Overlay 0
    - { index: 36, color: "#585b70" } # Surface 2
    - { index: 37, color: "#45475a" } # Surface 1
    - { index: 38, color: "#313244" } # Surface 0
    - { index: 39, color: "#1e1e2e" } # Base
    - { index: 40, color: "#181825" } # Mantle
    - { index: 41, color: "#11111b" } # Crust
