colors:
  # Default colors
  primary:
    background: '#282828'
    foreground: '#ebdbb2'

  # Colors which should be used to draw the terminal cursor.
  # Allowed values are CellForeground/CellBackground, which reference the
  # affected cell, or hexadecimal colors like #ff00ff.
  cursor:
    text: CellBackground
    cursor: CellForeground

  # Search colors
  # Colors used for the search bar and match highlighting.
  search:
    # Allowed values are CellForeground/CellBackground, which reference the
    # affected cell, or hexadecimal colors like #ff00ff.
    bar:
      foreground: '#282828'
      background: '#d79921'
    matches:
      foreground: '#282828'
      background: '#d79921'
    focused_match:
      foreground: '#282828'
      background: '#d79921'

  # Color used for the indicator displaying the position in history during
  # search and vi mode.
  line_indicator:
    foreground: '#282828'
    background: '#d79921'

  # Color used for the footer bar on the bottom, used by search regex input,
  # hyperlink URI preview, etc.
  footer_bar:
    background: '#282828'
    foreground: '#d79921'

  # Colors which should be used to draw the selection area.
  # Allowed values are CellForeground/CellBackground, which reference the
  # affected cell, or hexadecimal colors like #ff00ff.
  selection:
    text: '#d5c4a1'
    background: '#504945'

  # Normal colors
  normal:
    black:   '#282828'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#d79921'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#ebdbb2'

  # Bright colors
  bright:
    black:   '#3c3836'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#fbf1c7'
