colors:
  primary:
    background: '#060A17'
    foreground: '#B0BFBC'

  # Colors which should be used to draw the terminal cursor.
  # Allowed values are CellForeground/CellBackground, which reference the
  # affected cell, or hexadecimal colors like #ff00ff.
  cursor:
    text: CellBackground
    cursor: CellForeground

  # Normal colors
  normal:
    black:   '#060A17'
    red:     '#CF3709'
    green:   '#72892F'
    yellow:  '#F8990D'
    blue:    '#0B398E'
    magenta: '#93588F'
    cyan:    '#459EA6'
    white:   '#5E7173'

  # Bright colors
  bright:
    black:   '#141929'
    red:     '#DB7E57'
    green:   '#88B073'
    yellow:  '#DBB956'
    blue:    '#04628B'
    magenta: '#B38BC3'
    cyan:    '#A1D0C8'
    white:   '#B0BFBC'
