
# Set up Unicode
export LANG=en_US.UTF-8

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:/usr/local/bin:$HOME/Workspace/bin"

# Set up custom PS1
autoload -U colors && colors
PS1="%{$fg[magenta]%}[%T]%{$reset_color%} %m %{$fg[yellow]%}%~ %{$reset_color%}$ "

# Add colors to ls output
export CLICOLOR=1

# Simple Key Bindings
bindkey "^[[1;3C" forward-word
bindkey "^[[1;3D" backward-word

# History Configuration
HISTSIZE=5000               #How many lines of history to keep in memory
HISTFILE=~/.zsh_history     #Where to save history to disk
SAVEHIST=5000               #Number of history entries to save to disk
HISTDUP=erase               #Erase duplicates in the history file
setopt    appendhistory     #Append history to the history file (no overwriting)
setopt    sharehistory      #Share history across terminals
setopt    incappendhistory  #Immediately append to the history file, not just when a term is killed

# Load Bundles
source $HOME/Workspace/bin/antigen.zsh
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen apply
