theme = "catppuccin"

[editor]
line-number = "absolute"
mouse = true
auto-completion=true
auto-format=true
text-width=80
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.cursor-shape]
select = "underline"
normal = "block"
insert = "bar"

[editor.statusline]
left = ["mode", "separator", "file-name", "read-only-indicator", "file-modification-indicator"]
center = []
right = ["version-control", "spacer", "separator", "position", "separator", "file-type"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
d = ["yank_joined_to_clipboard", "yank", "delete_selection"]
y = ["yank_joined_to_clipboard", "yank"]
C-s = "split_selection_on_newline"
C-u = "switch_to_uppercase"
C-l = "switch_to_lowercase"
u = "undo"
r = "redo"
